name: Keep Supabase Awake

on:
  schedule:
    # Executa a cada 3 dias
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          curl -I https://pasmbmpgxuirnhlpwojf.supabase.co/rest/v1/
