name: Keep Supabase and Streamlit Awake

on:
  schedule:
    # Executa a cada 3 dias
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          curl -I https://pasmbmpgxuirnhlpwojf.supabase.co/rest/v1/

      - name: Ping Streamlit App
        run: |
          curl -s https://caixa-facil-ervhiqc8bigpprp5zjzvra.streamlit.app > /dev/null
